name: freelance_dashboard
description: "Freelance Dashboard for Freelancers and agencies to track contracts and projects."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.14.0         # Firebase Core
  firebase_auth: ^5.6.0          # Firebase Authentication
  cloud_firestore: ^5.6.9         # Cloud Firestore :contentReference[oaicite:1]{index=1}
  provider: ^6.0.5                # State management
  intl: ^0.20.2                   # Internationalization
  csv: ^6.0.0                     # CSV encoding/decoding :contentReference[oaicite:2]{index=2}
  printing: ^5.11.0               # Print & PDF rendering
  pdf: ^3.11.3                    # PDF creator
  shared_preferences: ^2.5.3      # Key-value storage
  flutter_switch: ^0.3.2          # iOS-style switches
  #charts_flutter: ^0.5.2         # Chart widgets
  #path_provider: ^2.1.5        # Filesystem paths
  share_plus: ^11.0.0             # Cross-platform sharing
  flutter_hooks: ^0.21.2          # Flutter Hooks
  flutter_pdfview: ^1.4.1+1       # Native PDF viewer :contentReference[oaicite:3]{index=3}
  table_calendar: ^3.2.0
  fl_chart: ^0.71.0
  file_picker: ^10.2.0
  firebase_storage: ^12.4.7
  flutter_animate: ^4.3.0
  lottie: ^3.3.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
      - assets/animations/splash_animation.json


  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
