// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1aPRy_CM715luVmCgD2vUBUPz4UfZxlY',
    appId: '1:76039526935:web:c8534744c7e48966441a52',
    messagingSenderId: '76039526935',
    projectId: 'freelance-dashboard-41096',
    authDomain: 'freelance-dashboard-41096.firebaseapp.com',
    storageBucket: 'freelance-dashboard-41096.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_-CMAYEPZopF3QQ8XB1OoLr02LpsBdSc',
    appId: '1:76039526935:android:2c5e64308783396f441a52',
    messagingSenderId: '76039526935',
    projectId: 'freelance-dashboard-41096',
    storageBucket: 'freelance-dashboard-41096.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAECTbUsvWzgKAaUewdFxasCv-sV3LuHo4',
    appId: '1:76039526935:ios:18117b60800ca67d441a52',
    messagingSenderId: '76039526935',
    projectId: 'freelance-dashboard-41096',
    storageBucket: 'freelance-dashboard-41096.firebasestorage.app',
    iosBundleId: 'com.example.freelanceDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAECTbUsvWzgKAaUewdFxasCv-sV3LuHo4',
    appId: '1:76039526935:ios:18117b60800ca67d441a52',
    messagingSenderId: '76039526935',
    projectId: 'freelance-dashboard-41096',
    storageBucket: 'freelance-dashboard-41096.firebasestorage.app',
    iosBundleId: 'com.example.freelanceDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1aPRy_CM715luVmCgD2vUBUPz4UfZxlY',
    appId: '1:76039526935:web:8219be23028f3df2441a52',
    messagingSenderId: '76039526935',
    projectId: 'freelance-dashboard-41096',
    authDomain: 'freelance-dashboard-41096.firebaseapp.com',
    storageBucket: 'freelance-dashboard-41096.firebasestorage.app',
  );
}
